---
spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/coupon?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 50
      max-lifetime: 30000
      username: root
      password: 0913
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    sql:
      debug

---
spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS coupon;
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    sql:
      debug

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/coupon?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 10
      max-lifetime: 30000
      username: root
      password: 0913
