spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      port: 6379
      host: localhost
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/coupon?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 50
      max-lifetime: 30000
      username: wave
      password: 0913
  jpa:
    hibernate:
      ddl-auto: create
logging:
  level:
    sql:
      debug