spring:
  datasource:
    hikari:
      maximum-pool-size: 5
    url: jdbc:mysql://localhost:3306/coupon?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: wave
    password: 0913
    driver-class-name: